# Site settings
title: Wei Wong
description: SaaS sales rep, software engineer, and aspiring polymath. Interested in technology as a function to drive change in the world.
url: "https://weijwong.com"
baseurl: ""
image: /images/chaoscanvas-1.png

# Author
author:
  name: Wei Wong
  twitter: weijwong

# Social links
twitter_username: weijwong
substack_url: https://weiwong.substack.com/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
twitter:
  username: weijwong
  card: summary_large_image

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
